version: '3'

services:
  app:
    build: .
    volumes:
      - .:/mapbiomas
    env_file: .env
    command: sleep infinity
    links: 
      - db:database

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


volumes:
  postgres-data:
